import 'package:flutter/material.dart';
Color backgroundColor1 = const Color(0xffE9EAF7);
Color backgroundColor2 = const Color(0xffF4EEF2);
Color backgroundColor3 = const Color(0xffEBEBF2);
Color backgroundColor4 = const Color(0xffE3EDF5);
Color primaryColor = const Color(0xffD897FD);
Color textColor1 = const Color(0xff353047);
Color textColor2 = const Color(0xff6F6B7A);
Color buttonColor = const Color(0xffFD6B68);
Color newText = const Color(0xff212121);
Color newBackground = const Color(0xffF5F5F5);
Color secondaryColor = const Color(0xffFFAEBC);
Color secondaryTextColor = const Color(0xff757575);
Color primaryColor2 = const Color(0xff6C8CFF);
